"""initial schema

Revision ID: 2b1841a4425f
Revises: 
Create Date: 2026-09-07 11:56:24.781473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1841a4425f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('organizing_doctors', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('cme_credits', sa.Boolean(), nullable=False),
    sa.Column('approx_duration_hours', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('import_batches',
    sa.Column('batch_id', sa.String(length=32), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('imported_by', sa.String(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('participants',
    sa.Column('participant_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('whatsapp_number', sa.String(), nullable=False),
    sa.Column('place_of_work', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('medical_license_no', sa.String(), nullable=True),
    sa.Column('participant_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('participant_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_ref', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('certificates',
    sa.Column('certificate_id', sa.String(length=32), nullable=False),
    sa.Column('certificate_no', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('participant_id', sa.String(length=32), nullable=False),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.participant_id'], ),
    sa.PrimaryKeyConstraint('certificate_id'),
    sa.UniqueConstraint('event_id', 'certificate_no'),
    sa.UniqueConstraint('event_id', 'participant_id')
    )
    op.create_table('event_certificate_counters',
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('last_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('import_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=32), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.batch_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrations',
    sa.Column('registration_id', sa.String(length=32), nullable=False),
    sa.Column('participant_id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.participant_id'], ),
    sa.PrimaryKeyConstraint('registration_id'),
    sa.UniqueConstraint('participant_id', 'event_id')
    )
    op.create_table('attendance',
    sa.Column('attendance_id', sa.String(length=32), nullable=False),
    sa.Column('registration_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sign_in_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sign_in_signature_ref', sa.String(), nullable=False),
    sa.Column('sign_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sign_out_signature_ref', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.registration_id'], ),
    sa.PrimaryKeyConstraint('attendance_id'),
    sa.UniqueConstraint('registration_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_table('registrations')
    op.drop_table('import_errors')
    op.drop_table('event_certificate_counters')
    op.drop_table('certificates')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('participants')
    op.drop_table('import_batches')
    op.drop_table('events')
    # ### end Alembic commands ###
